<a href="https://colab.research.google.com/github/Clustering-Crew/UNIV-6080-Notebooks/blob/main/DeterminantAndTrace_Exercise_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Credit*: some material here has been adapted from [Sam Roweis](https://www.cs.nyu.edu/home/people/in_memoriam/samroweis.html)' [Linear Algebra Review](http://www.cs.ubc.ca/~murphyk/Teaching/Papers/roweis_linAlgebra.ps).

In [ ]:
import numpy as np

# Determinant and Trace

The determinant and trace are two important properties of square ($n \times n$) matrices.

## Determinants

The matrix *determinant* is a scalar quantity, normally denoted $|A|$ or $\text{det}(A)$ whose absolute value measures how much the matrix "stretches" or "squishes" volume as it transforms its inputs to outputs and whose sign indicates whether the transformation is [orientation preserving](http://en.wikipedia.org/wiki/Orientation_%28vector_space%29). Matrices with large determinants do (on average) a lot of stretching and those with small determinants do a lot of squishing.

Matrices with zero determinant have rank less than the number of rows and and actually collapse some of their input space into a line or hyperplane (pancake) in the output space, and this can be thought of doing "infinite squishing". Conventionally, the determinant is only defined for square matrices, but there is a natural extension to rectangular ones using the *singular value decomposition*.

### Determinant of a full-rank (invertible) matrix

Determinants can be computed via `numpy.linalg.det`. Let's compute the determinant for matrix

$$
\mathbf{A} =
\begin{bmatrix}
2 && 3 && 0\\
3 && 2 && 7\\
2 && 1 && 6
\end{bmatrix}
$$

In [ ]:
A = np.array([[2, 3, 0], [3, 2, 7], [2, 1, 6]])
print(A)
print(np.linalg.det(A))
print(np.linalg.det(np.linalg.inv(A)))  # note 1/det(A)


[[2 3 0]
 [3 2 7]
 [2 1 6]]
-2.000000000000006
-0.49999999999999917


### Determinant of a rank deficient matrix

A rank deficient matrix will have determinant of zero. Let's compute the determinant for matrix

$$
\mathbf{B} =
\begin{bmatrix}
2 & 3 & 2\\
1 & 2 & 4\\
3 & 5 & 6
\end{bmatrix}
$$

In [ ]:
B = np.array([[2, 3, 2], [1, 2, 4], [3, 5, 6]])
print(np.linalg.matrix_rank(B))
print(B)
print(np.linalg.det(B))  # not quite zero because of numerical instability

2
[[2 3 2]
 [1 2 4]
 [3 5 6]]
2.664535259100367e-15


### Exercise

Show in another way that $\mathbf{B}$ is rank deficient.

In [ ]:
# A matrix can be proved rank deficient if its inverse doesn't exist.

print(np.linalg.cond(B))
print(np.__version__)

def check_rank_deficient(matrix: np.array) -> bool:
    """ Function to check if a matrix is rank deficient through inverse calculation """
    matrix_i = np.linalg.inv(matrix)
    print(matrix_i)

    if matrix_i is None or np.linalg.cond(B) > 1e11: return False

    return True

# print(check_rank_deficient(B))

test_matrix_sig = np.array([[1, 2, 0], [3, -1, 2], [-2, 3, -2]]) # Singular matrix

print(check_rank_deficient(test_matrix_sig))

3.5996351261407976e+16
2.0.2


LinAlgError: Singular matrix

## Trace

The trace of a square matrix is simply the sum of its diagonal elements:

$$\mathrm{tr}(\mathbf{A}) = \sum_{i=1}^n a_{ii}.$$

It can be computed using `numpy.trace`.

In [ ]:
print(np.trace(A))
print(np.diag(A).sum())

10
10


Note that $\mathrm{tr}(\mathbf{A}\mathbf{B}) = \mathrm{tr}(\mathbf{B}\mathbf{A})$ even if $\mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A}$. This property generalizes to products of an arbitrary number of matrices. The trace is invariant under cyclic permutations.

In [ ]:
np.allclose(np.trace(A.dot(B)),np.trace(B.dot(A)))

True