<a href="https://colab.research.google.com/github/Clustering-Crew/UNIV-6080-Notebooks/blob/main/EigendecompositionAndDiagonalization_With_Exercise_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.linalg import inv

# Eigendecomposition and Diagonalization

Let's work through Example 4.11 using NumPy.

We would like to compute the eigendecomposition of
$
\mathbf{A} =
\begin{bmatrix}
2 & 1\\
1 & 2
\end{bmatrix}
$.

Step 1 is to compute eigenvalues and eigenvectors. Instead of using the characteristic polynomial, we will use `numpy.eig`:

In [ ]:
A = np.array([[2, 1], [1, 2]])
d, P = np.linalg.eig(A)
print(d)
print(P)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


Step 2 is to check for existence. The eigenvectors
$
\frac{1}{\sqrt{2}}
\begin{bmatrix}
1\\
-1
\end{bmatrix}
$
and
$
\frac{1}{\sqrt{2}}
\begin{bmatrix}
1\\
1
\end{bmatrix}
$
form a basis of $\mathbb{R}^2$. Therefore $\mathbf{A}$ can be diagonalized.



Step 3 is to construct the matrix $P$ to diagonalize $A$. `numpy.eig` already returns the eigenvectors as the columns of a matrix, so we are good to go. Let's form $\mathbf{D} = \mathbf{P}^{-1}\mathbf{A}\mathbf{P}$:

In [ ]:
D = np.linalg.multi_dot([inv(P), A, P])
print(D)

[[ 3.00000000e+00 -1.01465364e-17]
 [-3.04396091e-17  1.00000000e+00]]


## Geometric intuition for the eigendecomposition

We have successfully diagonalized $\mathbf{A}$. Let's verify that applying the linear mapping represented by $\mathbf{A}$ to a vector $\mathbf{x} =
\begin{bmatrix}
1 & 1
\end{bmatrix}^{\top}
$ is equivalent to first applying a change of basis, then scaling, then undoing the change of basis.

In [ ]:
x = np.array([1, 1])
np.dot(A, x)

array([3, 3])

First, the change of basis:

In [ ]:
b = np.dot(inv(P), x)
print(b)

[1.41421356 0.        ]


Now the scaling:

In [ ]:
b_scaled = np.dot(D, b)
print(b_scaled)

[ 4.24264069e+00 -4.30481080e-17]


Now undoing the change of basis:

In [ ]:
np.dot(P, b_scaled)

array([3., 3.])

We see that this is equivalent to the linear mapping with $\mathbf{A}$.

### Exercise

We read that if the eigendecomposition exists, then the determinant can easily be computed as

$$
\det(\mathbf{A}) = \det(\mathbf{PDP}^{-1})=\det(\mathbf{P})\det(\mathbf{D})\det(\mathbf{P}^{-1})
$$

Since $\mathbf{D}$ is diagonal, we know that its determinant is simply the product of its diagonal elements. But why is it easy to compute the determinant of $\mathbf{P}$ or $\mathbf{P}^{-1}$?

### Answer

From equation 4.63a and 4.63b, the equation can be further simplified into just $\det(\mathbf{D})$ because, since $\mathbf{P}$ is an orthogonal matrix, therefore $\det(\mathbf{P}^{-1}) = \dfrac{1}{\det(\mathbf{P})}$ and they cancel out each other.