<a href="https://colab.research.google.com/github/Clustering-Crew/UNIV-6080-Notebooks/blob/main/LinearIndependence_(With_Exercise_solution).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Linear Independence

Let's see a few different ways to test for linear independence of a set of vectors. We will start with the set of vectors from Example 2.15 in the text:

$$
\left\{
\begin{bmatrix} 1\\ -2\\ 1 \\ -1 \end{bmatrix},
\begin{bmatrix} -4\\ -2\\ 0 \\  4 \end{bmatrix},
\begin{bmatrix} 2\\ 3\\  -1\\ -3 \end{bmatrix}
\begin{bmatrix} 17\\ -10\\  11\\ 1 \end{bmatrix}
\right\}
$$

In [ ]:
A = np.array([[1, -2, 1, -1], [-4, -2, 0, 4], [2, 3, -1, -3], [17, -10, 11, 1]]).T
print(A)

[[  1  -4   2  17]
 [ -2  -2   3 -10]
 [  1   0  -1  11]
 [ -1   4  -3   1]]


The simplest way to test for linear independence is by way of `numpy.linalg.matrix_rank`. This will report the number of linearly independent columns.

In [ ]:
np.linalg.matrix_rank(A)

np.int64(3)

We see that only three columns are linearly independent.

`np.linalg.matrix_rank` actually employs the Singular Value Decomposition and tests whether the magnitude of the singular values of the matrix exceed some tolerance close to zero. Let's actually run this ourselves.

In [ ]:
U, s, V = np.linalg.svd(A)
print(s)

[2.27926405e+01 7.39086258e+00 1.69431087e+00 1.28342054e-15]


In [ ]:
# this is the default tolerance, see the documentation for numpy.linalg.matrix_rank
tol = s.max() * max(A.shape) * np.finfo(s.dtype).eps
print(tol)
print(s > tol)

2.0243931419600192e-14
[ True  True  True False]


We see that the fourth singular value does not pass the test. This is because the last column can be expressed as a linear combination of the three others.

## Exercise

Another way to test for linear independence is to reduce the matrix to reduced row echelon form and count the pivot columns. This is similar to what was done in Example 2.15 in the text. See if you can use the `sympy` package to do this in Python. Hint: check out the `rref` function.

In [ ]:
from sympy.matrices import Matrix
from typing import Tuple


def calc_rref_rank(matrix: Matrix) -> Tuple[Matrix, int]:
    """ Function to calculate RREF and rank of a matrix"""
    # No. of columns
    n_cols = matrix.shape[1]

    # calculate RREF and pivot columns
    RREF, pivot_columns = matrix.rref()

    # Rank of the matrix
    rank = len(pivot_columns)

    # return RREF and rank
    return RREF, rank


In [ ]:
# Convert the numpy array to Matrix class
matrix = Matrix(A)

# Funtion call
RREF, rank = check_dependence(matrix)

print(f"Row Reduced Echelon Form: {RREF}\n")

# pivot_columns
print(f"No. of linearly independent vectors: {rank}\n")

# Check if the system is linearly independent
assert (rank <= matrix.shape[0]), "This is an impossible case" # Check if no. of cols >= rank
print("System is linearly independent") if (matrix.shape[1] == rank) else print("System is linearly dependent")


Row Reduced Echelon Form: Matrix([[1, 0, 0, -7], [0, 1, 0, -15], [0, 0, 1, -18], [0, 0, 0, 0]])

No. of linearly independent vectors: 3

System is linearly dependent
