<a href="https://colab.research.google.com/github/Clustering-Crew/UNIV-6080-Notebooks/blob/main/Orthogonality_With_Exercise_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Orthogonality

## Finding an orthogonal basis

The Gram-Schmidt process is a method for converting a set of basis vectors that are linearly independent but not necessarily orthogonal to an orthogonal set that spans the same subspace.

The procedure goes through each basis vector, subtracting off any components in the direction of the previously visited vectors, and then scales the remainder to be unit rank.

The [Wikipedia page on Gram-Schmidt](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process) has a nice animation of it applied in $\mathbb{R}^3$.


In [ ]:
# Source: https://gist.github.com/iizukak/1287876/edad3c337844fac34f7e56ec09f9cb27d4907cc7#gistcomment-2935521
def gram_schmidt(A):
    """Orthogonalize a set of vectors stored as the columns of matrix A."""
    # Get the number of vectors.
    n = A.shape[1]
    Q = A.copy()
    for j in range(n):
        # To orthogonalize the vector in column j with respect to the
        # previous vectors, subtract from it its projection onto the
        # each of the previous vectors.
        for k in range(j):
            Q[:, j] -= np.dot(Q[:, k], Q[:, j]) * Q[:, k]
        Q[:, j] = Q[:, j] / np.linalg.norm(Q[:, j])
    return Q

Let's apply the Gram-Schmidt process to the following basis:

$$
\left\{
\begin{bmatrix} 1\\ 1\\ 2 \end{bmatrix},
\begin{bmatrix} 1\\ 3\\ -1\\ \end{bmatrix},
\begin{bmatrix} 0\\ 1\\  1\\\end{bmatrix}
\right\}
$$

In [ ]:
A = np.array([[1.0, 1.0, 0.0], [1.0, 3.0, 1.0], [2.0, -1.0, 1.0]])
Q = gram_schmidt(A)
print(Q)

[[ 0.40824829  0.20739034 -0.88900089]
 [ 0.40824829  0.82956136  0.38100038]
 [ 0.81649658 -0.51847585  0.25400025]]


We can see that the columns of Q are orthogonal and are of unit norm:

In [ ]:
print(np.dot(Q[:, 0], Q[:, 1]))
print(np.dot(Q[:, 0], Q[:, 2]))
print(np.dot(Q[:, 1], Q[:, 2]))
for i in range(Q.shape[1]):
  print(np.linalg.norm(Q[:, i]))

-1.1102230246251565e-16
-3.608224830031759e-16
1.3877787807814457e-16
1.0
0.9999999999999999
0.9999999999999999


### Exercise

At each step of the Gram-Schmidt process, we project a vector onto each of the previously computed vectors and subtract these components. The projection operator of vector $\mathbf{v}$ onto vector $\mathbf{u}$ is defined as

$$\text{proj}_{\mathbf{u}}(\mathbf{v}) = \frac{\langle \mathbf{v}, \mathbf{u} \rangle}{\langle \mathbf{u}, \mathbf{u} \rangle} \mathbf{u}$$

We see this implemented on the line

```
Q[:, j] -= np.dot(Q[:, k], Q[:, j]) * Q[:, k]
```

above. How come we are missing the denominator, $\langle\mathbf{u}, \mathbf{u} \rangle = \|\mathbf{u}\|^2$?

## Answer

According to the theory, it is true that the norm term is missing in the code implementation. However, there is a normalization step implemented after the inner loops. When we simulate the outer and inner loop we can find that those *k* vectors are already in orthonormal form. Therefore the denominator is safely omitted.

---
</br>

The Gram-Schmidt process is simple, but numerically unstable and therefore not recommended in practice. Fortunately NumPy provides a more powerful method, `numpy.linalg.qr` which will compute an orthonormal basis:

In [ ]:
Qnew, _ = np.linalg.qr(A)
print(Qnew)

[[-0.40824829 -0.20739034 -0.88900089]
 [-0.40824829 -0.82956136  0.38100038]
 [-0.81649658  0.51847585  0.25400025]]


Comparing the result from both approaches, we can see that the orthonormal basis is not unique.